### ISSUE TITLE
Why need a phase rotation?

### ISSUE THREAD

**Issue by cheny93921** [tomgoldstein/phasepack-matlab#5]
I am confused about the actual use of this code, here is an excerpt from the source code:

% Phase retrieval can only recover images up to a phase ambiguity. 
% Let's apply a phase rotation to align the recovered image with the 
% original so it looks nice when we display it.
rotation= sign(recovered_image(:)'*image(:));
recovered_image = rotation*recovered_image;

where "image" is the complex amplitude to be recovered. However, in the actual experiment "image" is unknown, so how should we modify the code in this case? By the way, simply commenting out these two lines of code does not work.

I would be very grateful if anyone could answer my doubts. @tomgoldstein @rohanchandra30

**Comment by tomgoldstein** [comment]
This demo is just meant to demonstrate that the code works, and to validate this visually.  We start with a (known) ground truth image, and then try to recover it.  The reason for aligning the recovered image is so that we can put it side-by-side with the ground truth and visually see that they are the same - i.e., we can visually see that phase retrieval worked and we got back what we started with.   This is only possible because we happen to know the ground truth.  

In practice, recovery of a signal from phaseless measurements is only possible up to the phase ambiguity. You don't know the ground truth, and so it's not possible to know what the phase ambiguity is.  For this reason, it's also not possible in realistic settings to know how accurately you have recovered the true (unknown, in this case) signal.  However, it is possible to measure whether you've solve the phase retrieval problem by measuring the residual  |A(x)|-b.  Just keep in mind that solving the phase retrieval problem (i.e., getting a residual of 0) doesn't mean you recovered the true signal; if the linear operator A is not well-conditioned or the number of measurements is too small the recovered signal could be of low quality.  

I'm not sure what you mean by "commenting out these two lines of code does not work."  Without those two lines, you have still recovered the solution up to phase ambiguity (the best you can ever hope to do without knowing the ground truth).

**Comment by cheny93921** [comment]
> This demo is just meant to demonstrate that the code works, and to validate this visually. We start with a (known) ground truth image, and then try to recover it. The reason for aligning the recovered image is so that we can put it side-by-side with the ground truth and visually see that they are the same - i.e., we can visually see that phase retrieval worked and we got back what we started with. This is only possible because we happen to know the ground truth.
> 
> In practice, recovery of a signal from phaseless measurements is only possible up to the phase ambiguity. You don't know the ground truth, and so it's not possible to know what the phase ambiguity is. For this reason, it's also not possible in realistic settings to know how accurately you have recovered the true (unknown, in this case) signal. However, it is possible to measure whether you've solve the phase retrieval problem by measuring the residual |A(x)|-b. Just keep in mind that solving the phase retrieval problem (i.e., getting a residual of 0) doesn't mean you recovered the true signal; if the linear operator A is not well-conditioned or the number of measurements is too small the recovered signal could be of low quality.
> 
> I'm not sure what you mean by "commenting out these two lines of code does not work." Without those two lines, you have still recovered the solution up to phase ambiguity (the best you can ever hope to do without knowing the ground truth).

**Comment by cheny93921** [comment]
Thanks for your detailed and thoughtful explanations. I'm doing a phase retrieval experiment recently, but the results are not satisfactory. The measurement operator we use is free-space propagation operator rather than a Fourier transform operator, because we don't know how to use MATLAB code to describe the Fourier transform introduced by lens. I think there are two main reasons for poor recovery:
1. As you mentioned, the linear operator A is not well-conditioned. In practice, we tried to adjust various parameters to optimize the results.
2. The one-to-one correspondence between mask and the diffraction pattern pixels seems to be particularly important, but in reality we can't accurately achieve this. Our theoretical simulations show that the mismatch between mask and diffraction pattern pixels will lead to poor recovery or even impossible to recover. Thus, I'm curious about how you accurately control their registration?


Best wishes!







------------------ 原始邮件 ------------------
发件人:                                                                                                                        "tomgoldstein/phasepack-matlab"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月25日(星期三) 上午10:27
收件人:&nbsp;"tomgoldstein/phasepack-matlab"<phasepack-matlab@noreply.github.com&gt;;
抄送:&nbsp;"cheny"<1484654436@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [tomgoldstein/phasepack-matlab] Why need a phase rotation? (#5)





 
This demo is just meant to demonstrate that the code works, and to validate this visually.  We start with a (known) ground truth image, and then try to recover it.  The reason for aligning the recovered image is so that we can put it side-by-side with the ground truth and visually see that they are the same - i.e., we can visually see that phase retrieval worked and we got back what we started with.   This is only possible because we happen to know the ground truth.
 
In practice, recovery of a signal from phaseless measurements is only possible up to the phase ambiguity. You don't know the ground truth, and so it's not possible to know what the phase ambiguity is.  For this reason, it's also not possible in realistic settings to know how accurately you have recovered the true (unknown, in this case) signal.  However, it is possible to measure whether you've solve the phase retrieval problem by measuring the residual  |A(x)|-b.  Just keep in mind that solving the phase retrieval problem (i.e., getting a residual of 0) doesn't mean you recovered the true signal; if the linear operator A is not well-conditioned or the number of measurements is too small the recovered signal could be of low quality.
 
I'm not sure what you mean by "commenting out these two lines of code does not work."  Without those two lines, you have still recovered the solution up to phase ambiguity (the best you can ever hope to do without knowing the ground truth).
